version: "3.7"

services:
    fpm:
        build:
            args:
                user: ${FPM_USER_NAME}
                uid: ${FPM_UID}
            context: ./php
            dockerfile: Dockerfile
        image: ${DOCKER_NAME}-fpm-image
        container_name: ${DOCKER_NAME}-fpm
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ../:/var/www
        networks:
            - keep-notes

    mysql:
        image: mysql:8.0
        container_name: ${DOCKER_NAME}-mysql
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_USER: ${DB_USERNAME}
        volumes:
            - ../:/var/www
            - ./data/mysql:/var/lib/mysql
        ports:
            - "${DB_PORT}:${DB_PORT}"
        networks:
            - keep-notes

    nginx:
        image: nginx:1.17-alpine
        container_name: ${DOCKER_NAME}-nginx
        hostname: ${APP_DOMAIN}
        restart: unless-stopped
        ports:
            - "80:80"
        volumes:
            - ../:/var/www
            - ./nginx:/etc/nginx/conf.d
        networks:
            - keep-notes

networks:
    keep-notes:
        driver: bridge
